server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:      
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/javabase
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: false
